### ISSUE TITLE
GetMail Unread not working 

### ISSUE THREAD

**Issue by arasumiyan** [open-rpa/openrpa#321] opened 2020-05-27 17:16 UTC
The GetMail Unread mail is not working- When I set UnreadOnly  true/false same email count getting 
 and Move email item also not working . Please let me know how to proceed on this . Thanks

**Comment by skadefro** [comment] 2020-05-27 17:19
A reproducable workflow would help.

**Comment by arasumiyan** [comment] 2020-05-27 18:48
I'm sorry. I did not understand. Please elaborate

> A reproducable workflow would help.

**Comment by skadefro** [comment] 2020-05-27 18:50
Create a simple workflow that shows the bug, export it and upload here, so i can see the bug

**Comment by arasumiyan** [comment] 2020-05-27 19:28
Thanks for fast response @skadefro. Now its working fine both Unreadmail /move email after closed/reopened my OpenRPA.

**Comment by skadefro** [comment] 2020-05-27 19:33
Good to hear. Closing since is solved.

**Closed by skadefro** 2020-05-27 19:33 UTC
